# Generated by Django 6.0.3 on 2026-03-31 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('FACEBOOK', 'Facebook'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost'), ('WON', 'Won')], default='NEW', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='leads_organiz_d92ede_idx'), models.Index(fields=['organization', 'created_at'], name='leads_organiz_4b265e_idx'), models.Index(fields=['organization', 'email'], name='leads_organiz_b00fef_idx')],
            },
        ),
    ]
