# Generated by Django 6.0.3 on 2026-03-28 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('rep', 'Rep')], default='rep', max_length=20),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_e82976_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'role'], name='organizatio_user_id_a5406f_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization_membership'),
        ),
    ]
